version: '3.9'
services:
  webui:
    container_name: crediwise-webui
    build:
      context: ./webui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
    image: crediwise-webui:latest
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
